name: renew insta token

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
  
  workflow_dispatch:

jobs:
  renew_token:
    runs-on: ubuntu-20.04
    steps:
    - name: renew token
      run:  curl -v https://ig.instant-tokens.com/users/1fa1e484-8a56-44cf-aa6f-042211802e80/instagram/17841400905223262/token?userSecret=1lzozvypyovehssq94skrt > token.json
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ../../../src/assets/token.json
